---
- hosts: cisco
  connection: local
  gather_facts: False

  vars:
    cli:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: cli

  tasks:
    - name: Run show run
      ios_command:
        commands: show run
        provider: "{{ cli }}"

      register: output
      
    - debug: var=output

    - local_action: copy content="{{ output.stdout_lines }}" dest="./{{ inventory_hostname }}.show"

    # - name: run multiple commands and evaluate the output
    #   ios_command:
    #     commands:
    #       - show class-map
    #       - show policy-map
    #     wait_for:  
    #       - result[0] contains default  
    #     provider: "{{ cli }}"    

    #   register: output

    # - debug: var=output    
