---
- hosts: localhost
  tasks:
  - name: Generate qos switch configuration files
    template: src=./voice-qos-template.j2
                dest=./QOS_CFGS/{{item.hostname}}.cfg
    with_items:
      - { hostname: arctic-rtr01, int_list: ["GigabitEthernet3", "GigabitEthernet4"], testloop: 1.1.1.1 }
      - { hostname: csr1, int_list: ["GigabitEthernet3", "GigabitEthernet4"], testloop: 1.1.1.2 }
      - { hostname: csr2, int_list: ["GigabitEthernet3", "GigabitEthernet4"], testloop: 1.1.1.3 }
      - { hostname: csr3, int_list: ["GigabitEthernet3", "GigabitEthernet4"], testloop: 1.1.1.4 }
      - { hostname: csr4, int_list: ["GigabitEthernet3", "GigabitEthernet4"], testloop: 1.1.1.5 }
      - { hostname: csr5, int_list: ["GigabitEthernet3", "GigabitEthernet4"], testloop: 1.1.1.6 }
      - { hostname: csr6, int_list: ["GigabitEthernet3", "GigabitEthernet4"], testloop: 1.1.1.7 }
       
