---
# Validate QoS Configuration
- hosts: cisco
  connection: local
  gather_facts: False

  vars:
    cli:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: cli

    qos_qa:
        pmap: QOS-VOICE-PRIORITY
        ips2ping: ["1.1.1.1", "1.1.1.2"]

  tasks:
    - name: Baseline
      ios_command:
        commands: "{{ item }}"
        provider: "{{ cli }}"

      with_items:
      - "show run class-map"
      - "show run policy-map"
      - "show policy-map interface"
      - "show policy-map {{ qos_qa.pmap }}"

      register: output

    - debug: var=output

    - local_action: copy content="{{ output }}" dest="./{{ inventory_hostname }}.qaqos"

# ping ip 1.1.1.1 tos 184 validate repeat 100     